"""Inference utilities for saved Credit Score model artifacts."""

from __future__ import annotations

from pathlib import Path

import joblib
import pandas as pd

from creditscore.config import CONFIG, ExperimentConfig
from creditscore.preprocessing import CreditScoreDataPipeline
from creditscore.training import ModelArtifact


class CreditScorePredictor:
    """Loads champion artifacts and generates default-risk predictions.

    Args:
        artifact_path: Path to a .joblib artifact generated by
            ChampionModelTrainer.
        config: Experiment settings.

    Attributes:
        artifact: Loaded model artifact.
        pipeline: Deterministic data preparation pipeline.
    """

    def __init__(self, artifact_path: str | Path, config: ExperimentConfig = CONFIG):
        self.artifact_path = Path(artifact_path)
        self.config = config
        self.artifact: ModelArtifact = joblib.load(self.artifact_path)
        self.pipeline = CreditScoreDataPipeline(config)

    def prepare(self, df_raw: pd.DataFrame) -> pd.DataFrame:
        """Prepares raw input rows and aligns columns to the artifact.

        Args:
            df_raw: Raw dataframe with the same schema as train.csv. TARGET can
                be present or absent.

        Returns:
            Feature dataframe containing only the columns required by the model.
        """

        prepared = self.pipeline.prepare(df_raw)
        if self.config.target_col in prepared.columns:
            prepared = prepared.drop(columns=[self.config.target_col])

        for feature in self.artifact.features:
            if feature not in prepared.columns:
                prepared[feature] = pd.NA
        return prepared[self.artifact.features]

    def predict_proba(self, df_raw: pd.DataFrame) -> pd.Series:
        """Computes default probabilities.

        Args:
            df_raw: Raw dataframe with client records.

        Returns:
            Series with probability of TARGET=1.
        """

        X = self.prepare(df_raw)
        probabilities = self.artifact.model.predict_proba(X)[:, 1]
        return pd.Series(probabilities, index=df_raw.index, name="probabilidade_inadimplencia")

    def predict(self, df_raw: pd.DataFrame, threshold: float | None = None) -> pd.DataFrame:
        """Computes probabilities and binary predictions.

        Args:
            df_raw: Raw dataframe with client records.
            threshold: Optional custom threshold. If not provided, the artifact
                threshold is used.

        Returns:
            Dataframe with probabilities, predicted class and artifact metadata.
        """

        used_threshold = self.artifact.threshold if threshold is None else threshold
        probabilities = self.predict_proba(df_raw)
        result = pd.DataFrame(
            {
                "modelo": self.artifact.model_name,
                "probabilidade_inadimplencia": probabilities,
                "threshold": used_threshold,
                "predicao_target": (probabilities >= used_threshold).astype(int),
            },
            index=df_raw.index,
        )
        return result

