"""Training utilities for the two champion Credit Score models."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import pandas as pd
from xgboost import XGBClassifier

from creditscore.config import CONFIG, FINAL_MODEL_METRICS, ExperimentConfig
from creditscore.preprocessing import CreditScoreDataPipeline


@dataclass
class ModelArtifact:
    """Serializable object stored with each trained model.

    Attributes:
        model_name: Human-readable model identifier.
        model: Fitted estimator implementing predict_proba.
        features: Ordered list of features expected by the estimator.
        threshold: Operational threshold used to convert probabilities to 0/1.
        metrics: Holdout metrics obtained during the project experiments.
        notes: Additional explanation about how the model was selected.
    """

    model_name: str
    model: Any
    features: list[str]
    threshold: float
    metrics: dict[str, float]
    notes: str


class ChampionModelTrainer:
    """Trains and saves the selected champion models.

    Args:
        config: Experiment settings.
        ranking_path: CSV file with feature ranking generated by SHAP/importances.
        optuna_params_path: CSV file with best Optuna parameters.
    """

    def __init__(
        self,
        config: ExperimentConfig = CONFIG,
        ranking_path: str | Path = "reports/tables/importance_selection_feature_ranking.csv",
        optuna_params_path: str | Path = "reports/tables/optuna_xgboost_best_params.csv",
    ):
        self.config = config
        self.ranking_path = Path(ranking_path)
        self.optuna_params_path = Path(optuna_params_path)
        self.pipeline = CreditScoreDataPipeline(config)

    def prepare_training_data(self, train_path: str | Path) -> tuple[pd.DataFrame, pd.Series]:
        """Loads and prepares the labeled training dataset.

        Args:
            train_path: Path to train.csv.

        Returns:
            Tuple containing prepared features and target.
        """

        df_raw = pd.read_csv(train_path)
        df_prepared = self.pipeline.prepare(df_raw)
        return self.pipeline.split_X_y(df_prepared)

    def load_top_features(self, top_n: int = 50) -> list[str]:
        """Loads the top-N feature list from the saved ranking table.

        Args:
            top_n: Number of features to keep.

        Returns:
            Ordered list with the top feature names.
        """

        ranking = pd.read_csv(self.ranking_path)
        return ranking.sort_values("rank").head(top_n)["feature"].tolist()

    def load_optuna_params(self) -> dict[str, Any]:
        """Loads the best Optuna parameters from CSV.

        Returns:
            Dictionary with XGBoost hyperparameters.
        """

        params = pd.read_csv(self.optuna_params_path).iloc[0].to_dict()
        params.pop("best_cv_average_precision", None)
        int_keys = {"n_estimators", "max_depth"}
        cleaned = {}
        for key, value in params.items():
            cleaned[key] = int(value) if key in int_keys else float(value)
        return cleaned

    def train_importance_xgboost_top50(self, X: pd.DataFrame, y: pd.Series) -> ModelArtifact:
        """Trains the AP champion with the top 50 selected features.

        Args:
            X: Prepared feature dataframe.
            y: Binary target.

        Returns:
            ModelArtifact with fitted XGBoost model and metadata.
        """

        selected_features = [feature for feature in self.load_top_features(50) if feature in X.columns]
        model = XGBClassifier(
            objective="binary:logistic",
            eval_metric="logloss",
            tree_method="hist",
            random_state=self.config.random_state,
            n_estimators=360,
            learning_rate=0.05,
            max_depth=5,
            min_child_weight=5,
            subsample=0.8,
            colsample_bytree=0.8,
            scale_pos_weight=4,
            reg_lambda=1.0,
            n_jobs=-1,
            verbosity=0,
        )
        model.fit(X[selected_features], y)
        metrics = FINAL_MODEL_METRICS["importance_xgboost_top50"]
        return ModelArtifact(
            model_name="ImportanceXGBoost_top50",
            model=model,
            features=selected_features,
            threshold=metrics["threshold"],
            metrics=metrics,
            notes="Champion by Average Precision on the holdout set.",
        )

    def train_optuna_xgboost(self, X: pd.DataFrame, y: pd.Series) -> ModelArtifact:
        """Trains the Optuna-selected XGBoost model.

        Args:
            X: Prepared feature dataframe.
            y: Binary target.

        Returns:
            ModelArtifact with fitted XGBoost model and metadata.
        """

        params = self.load_optuna_params()
        params.update(
            {
                "objective": "binary:logistic",
                "eval_metric": "logloss",
                "tree_method": "hist",
                "random_state": self.config.random_state,
                "n_jobs": -1,
                "verbosity": 0,
            }
        )
        features = list(X.columns)
        model = XGBClassifier(**params)
        model.fit(X[features], y)
        metrics = FINAL_MODEL_METRICS["optuna_xgboost"]
        return ModelArtifact(
            model_name="OptunaXGBoost",
            model=model,
            features=features,
            threshold=metrics["threshold"],
            metrics=metrics,
            notes="Champion by ROC-AUC among the XGBoost optimization experiments.",
        )

    def save_artifact(self, artifact: ModelArtifact, output_path: str | Path) -> Path:
        """Saves a model artifact to disk with joblib.

        Args:
            artifact: Fitted model artifact.
            output_path: Destination .joblib path.

        Returns:
            Path where the artifact was saved.
        """

        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(artifact, output)
        return output

    def train_and_save_all(self, train_path: str | Path, output_dir: str | Path) -> list[Path]:
        """Trains and saves both champion model artifacts.

        Args:
            train_path: Path to train.csv.
            output_dir: Directory where .joblib artifacts will be written.

        Returns:
            List of saved artifact paths.
        """

        X, y = self.prepare_training_data(train_path)
        output = Path(output_dir)
        artifacts = [
            self.train_importance_xgboost_top50(X, y),
            self.train_optuna_xgboost(X, y),
        ]
        return [
            self.save_artifact(artifact, output / f"{artifact.model_name.lower()}.joblib")
            for artifact in artifacts
        ]
